# Generated by Django 4.0.5 on 2022-06-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_text_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='text_table',
            name='label',
            field=models.CharField(default='no input', max_length=50),
        ),
    ]
