# Generated by Django 4.0.5 on 2022-06-24 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_text_table_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='text_table',
            name='lang',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
