# Generated by Django 4.0.5 on 2022-06-24 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_text_table_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='text_table',
            name='predicted',
            field=models.CharField(default='no input', max_length=50),
        ),
    ]
